const mongoose = require('mongoose');
const { APPOINTMENT_STATUS } = require('../utils/constants');

const appointmentSchema = new mongoose.Schema(
  {
    student: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
    counselor: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
    preferredDate: { type: Date, required: true },
    timeSlot: { type: String, required: true }, // "HH:MM-HH:MM", generated by slot picker, not free text
    consultationMode: { type: String, enum: ['online', 'offline', 'phone'], required: true },
    reason: { type: String, required: true, maxlength: 1000 },
    sessionId: { type: String, default: '' },
    status: {
      type: String,
      enum: Object.values(APPOINTMENT_STATUS),
      default: APPOINTMENT_STATUS.PENDING,
    },
    counselorNote: { type: String, default: '' },
    cancelReason: { type: String, default: '' },
    rating: { type: Number, min: 1, max: 5 },
    studentFeedback: { type: String, default: '' },
  },
  { timestamps: true }
);

appointmentSchema.index({ status: 1, counselor: 1 });
appointmentSchema.index({ counselor: 1, preferredDate: 1, timeSlot: 1 });

module.exports = mongoose.model('Appointment', appointmentSchema);